dataSources:
  ds0:
    driverClassName: com.mysql.cj.jdbc.Driver
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:mysql://localhost:3306/ds0
    username: root
    password: PasswordYash@1

rules:
  - !SINGLE
    tables:
      - ds0.t_user
props:
  show-sql :  true
